/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "flipkart-blue": "#2874f0",
        "flipkart-yellow": "#ff9f00",
        "flipkart-orange": "#fb641b",
        "flipkart-green": "#388e3c",
        "flipkart-bg": "#f1f3f6",
        "on-primary-fixed": "#001944",
        "secondary-fixed": "#ffddba",
        "tertiary-fixed-dim": "#4edea3",
        "secondary-fixed-dim": "#ffb866",
        "surface-container": "#e6eeff",
        "on-tertiary-fixed-variant": "#005236",
        "error": "#ba1a1a",
        "surface-bright": "#f8f9ff",
        "primary-fixed-dim": "#afc6ff",
        "on-secondary-fixed-variant": "#673d00",
        "on-background": "#121c2a",
        "on-surface-variant": "#424754",
        "outline": "#727786",
        "on-error-container": "#93000a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#2b1700",
        "on-tertiary-fixed": "#002113",
        "on-primary-fixed-variant": "#004299",
        "surface-container-low": "#eff4ff",
        "primary": "#0056c3",
        "background": "#f8f9ff",
        "surface-variant": "#d9e3f6",
        "primary-fixed": "#d9e2ff",
        "on-primary-container": "#fefcff",
        "surface-tint": "#0059c8",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#6ffbbe",
        "on-tertiary-container": "#f5fff6",
        "outline-variant": "#c2c6d6",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "secondary": "#875200",
        "on-tertiary": "#ffffff",
        "surface-container-high": "#dee9fc",
        "surface-container-highest": "#d9e3f6",
        "inverse-primary": "#afc6ff",
        "on-secondary-container": "#653c00",
        "surface": "#f4f6fc",
        "secondary-container": "#fd9e00",
        "tertiary": "#006947",
        "inverse-surface": "#27313f",
        "tertiary-container": "#00855b",
        "on-surface": "#121c2a",
        "on-primary": "#ffffff",
        "primary-container": "#1f6feb",
        "surface-dim": "#d0dbed"
      },
      borderRadius: {
        "none": "0px",
        "sm": "0.375rem",
        "DEFAULT": "0.5rem",
        "md": "0.75rem",
        "lg": "1rem",
        "xl": "1.25rem",
        "2xl": "1.5rem",
        "3xl": "2rem",
        "4xl": "2.5rem",
        "full": "9999px"
      },
      boxShadow: {
        "soft": "0 4px 20px -2px rgba(0, 0, 0, 0.05)",
        "soft-lg": "0 10px 30px -4px rgba(0, 0, 0, 0.08)",
        "soft-xl": "0 20px 40px -6px rgba(0, 0, 0, 0.12)",
        "glow-blue": "0 0 25px -5px rgba(0, 86, 195, 0.35)",
        "glow-amber": "0 0 25px -5px rgba(253, 158, 0, 0.35)",
      },
      spacing: {
        "space-xs": "0.25rem",
        "gutter": "0.5rem",
        "space-xl": "1.5rem",
        "margin": "0.75rem",
        "space-md": "0.75rem",
        "space-lg": "1rem",
        "space-sm": "0.5rem"
      },
      fontFamily: {
        "sans": ["Inter", "system-ui", "sans-serif"],
        "heading": ["Plus Jakarta Sans", "system-ui", "sans-serif"],
        "body": ["Inter", "system-ui", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "title-md": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "display-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
